### ISSUE TITLE
后端分页路径的bug

### ISSUE THREAD

**Issue by 1379** [hooxuu/sonic-theme-Journal#1]
能否具体描述下”Sonic后端分页模块返回的路径有些许小bug“ 这里的bug具体是什么。
我测试了一下，没有发现问题，可能是遗漏了什么地方？

**Comment by hooxuu** [comment]
普通文章分页没有问题，但是如果按照分类或者标签筛选后的文章在进行分页切换返回的路径前少了一个 /，导致会在浏览器现有url后再拼接返回的路径会造成404，且如果当前页面是第2页，上一页的href目前直接返回的项目根路径，丢失了路径中的/tag或者/category导致退出了按条件筛选
