### ISSUE TITLE
journals.tmpl没有生效

### ISSUE THREAD

**Issue by beyondtop** [hooxuu/sonic-theme-Journal#2]
journals.tmpl没有生效。发布的日志已经选择公开。在默认主题下可以显示。如：https://xuexi.chat/journals
另外，是否可以增加图库模板？
感谢。

**Comment by hooxuu** [comment]
已修复，重新下载主题上传或者更新[journals.tmpl](https://github.com/hooxuu/sonic-theme-Journal/blob/main/journals.tmpl)
